# syntax=docker/dockerfile:1

FROM oven/bun:1 AS build

WORKDIR /app

COPY front/package.json front/bun.lockb ./

RUN bun install --frozen-lockfile

COPY front .

RUN bun run build

FROM nginx:1.27-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
