[package]
name = "testutil"
version = "1.3.0"
edition = "2024"

[dependencies]
once_cell = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
