# Default config file for p2p node
#
# Note: all settings are optional - any missing values will be "filled" from the default values

# Addresses are "multiaddr"s - see the libp2p docs for more details:
# https://docs.rs/libp2p/latest/libp2p/struct.Multiaddr.html
laddr = "/ip4/0.0.0.0/tcp/0"

# Optionally specify other addresses to dial on startup
dial = ""

# The idle timeout in seconds (0 means `u64::MAX`)
idle-timeout-secs = 0
