import { ec as EC } from "elliptic";
import SHA256 from "crypto-js/sha256";
import Hex from "crypto-js/enc-hex";

const curve = new EC("secp256k1");
const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();
const SALT_LABEL = textEncoder.encode("hyli-notes-v1");
const HKDF_INFO = textEncoder.encode("hyli-notes:aes-gcm:key:v1");

export interface EncryptedNote {
  encryptedPayload: string; // Base64url-encoded JSON envelope
  ephemeralPubkey: string; // Compressed secp256k1 pubkey (66 hex chars)
}

interface NoteEnvelopeV1 {
  v: number;
  nonce: string;
  ciphertext: string;
  tag: string;
}

/**
 * Derives a recipient tag from a UTXO address (poseidon2-derived).
 * This is a one-way, non-reversible identifier used to query for notes.
 */
export function deriveRecipientTag(utxoAddress: string): string {
  const normalized = utxoAddress.replace(/^0x/i, "").toLowerCase();
  if (normalized.length !== 64) {
    throw new Error("UTXO address must be a 64-character hex string (32 bytes)");
  }

  const tagInput = normalized + ":recipient_tag";
  return SHA256(tagInput).toString(Hex);
}

/**
 * Encrypts a note for a recipient using:
 * - secp256k1 ECDH (ephemeral sender key)
 * - HKDF-SHA256 key derivation
 * - AES-256-GCM authenticated encryption
 */
export async function encryptNote(recipientPubkeyHex: string, noteData: unknown): Promise<EncryptedNote> {
  const normalizedRecipient = recipientPubkeyHex.replace(/^0x/i, "").toLowerCase();
  if (normalizedRecipient.length !== 64) {
    throw new Error("Recipient public key must be a 64-character hex string");
  }

  const ephemeralKey = curve.genKeyPair();
  const recipientPubkey = reconstructPublicKey(normalizedRecipient);

  const shared = ephemeralKey.derive(recipientPubkey);
  const sharedSecret = Uint8Array.from(shared.toArray("be", 32));

  const ephemeralCompressedHex = ephemeralKey.getPublic().encodeCompressed("hex").toLowerCase();
  const aesKey = await deriveAesGcmKey(
    sharedSecret,
    normalizedRecipient,
    ephemeralCompressedHex
  );

  const nonce = crypto.getRandomValues(new Uint8Array(12));
  const plaintext = textEncoder.encode(JSON.stringify(noteData));

  const encrypted = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv: toArrayBuffer(nonce), tagLength: 128 },
      aesKey,
      plaintext
    )
  );

  if (encrypted.length < 16) {
    throw new Error("Encryption failed: malformed AES-GCM output");
  }

  const ciphertext = encrypted.slice(0, encrypted.length - 16);
  const tag = encrypted.slice(encrypted.length - 16);

  const envelope: NoteEnvelopeV1 = {
    v: 1,
    nonce: bytesToBase64Url(nonce),
    ciphertext: bytesToBase64Url(ciphertext),
    tag: bytesToBase64Url(tag),
  };

  const envelopeBytes = textEncoder.encode(JSON.stringify(envelope));

  return {
    encryptedPayload: bytesToBase64Url(envelopeBytes),
    ephemeralPubkey: ephemeralCompressedHex,
  };
}

/**
 * Decrypts an encrypted note payload generated by `encryptNote`.
 */
export async function decryptNote(
  privateKeyHex: string,
  encryptedPayload: string,
  ephemeralPubkeyHex: string
): Promise<unknown> {
  const normalizedPrivate = privateKeyHex.replace(/^0x/i, "").toLowerCase();

  if (normalizedPrivate.length !== 64) {
    throw new Error("Private key must be a 64-character hex string");
  }

  const privateKey = curve.keyFromPrivate(normalizedPrivate, "hex");
  const ephemeral = parseEphemeralPublicKey(ephemeralPubkeyHex);

  const shared = privateKey.derive(ephemeral.point);
  const sharedSecret = Uint8Array.from(shared.toArray("be", 32));

  const recipientXHex = privateKey.getPublic().getX().toString(16).padStart(64, "0").toLowerCase();
  const aesKey = await deriveAesGcmKey(
    sharedSecret,
    recipientXHex,
    ephemeral.compressedHex
  );

  const envelopeBytes = base64UrlToBytes(encryptedPayload);
  const envelope = JSON.parse(textDecoder.decode(envelopeBytes)) as NoteEnvelopeV1;

  if (envelope.v !== 1) {
    throw new Error(`Unsupported encrypted note version: ${String(envelope.v)}`);
  }

  const nonce = base64UrlToBytes(envelope.nonce);
  const ciphertext = base64UrlToBytes(envelope.ciphertext);
  const tag = base64UrlToBytes(envelope.tag);

  if (nonce.length !== 12) {
    throw new Error(`Invalid nonce length: ${String(nonce.length)}`);
  }
  if (tag.length !== 16) {
    throw new Error(`Invalid tag length: ${String(tag.length)}`);
  }

  const combined = new Uint8Array(ciphertext.length + tag.length);
  combined.set(ciphertext, 0);
  combined.set(tag, ciphertext.length);

  const plaintext = new Uint8Array(
    await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: toArrayBuffer(nonce), tagLength: 128 },
      aesKey,
      toArrayBuffer(combined)
    )
  );

  return JSON.parse(textDecoder.decode(plaintext));
}

function reconstructPublicKey(xHex: string): ReturnType<EC.KeyPair["getPublic"]> {
  try {
    return curve.keyFromPublic("02" + xHex, "hex").getPublic();
  } catch {
    return curve.keyFromPublic("03" + xHex, "hex").getPublic();
  }
}

function parseEphemeralPublicKey(ephemeralHex: string): {
  point: ReturnType<EC.KeyPair["getPublic"]>;
  compressedHex: string;
} {
  const normalized = ephemeralHex.replace(/^0x/i, "").toLowerCase();

  if (normalized.length === 66 && (normalized.startsWith("02") || normalized.startsWith("03"))) {
    return {
      point: curve.keyFromPublic(normalized, "hex").getPublic(),
      compressedHex: normalized,
    };
  }

  if (normalized.length === 130 && normalized.startsWith("04")) {
    const point = curve.keyFromPublic(normalized, "hex").getPublic();
    return {
      point,
      compressedHex: point.encodeCompressed("hex").toLowerCase(),
    };
  }

  if (normalized.length === 64) {
    const point = reconstructPublicKey(normalized);
    return {
      point,
      compressedHex: point.encodeCompressed("hex").toLowerCase(),
    };
  }

  throw new Error("Ephemeral public key must be 66-char compressed, 130-char uncompressed, or 64-char x-coordinate hex");
}

async function deriveAesGcmKey(
  sharedSecret: Uint8Array,
  recipientXHex: string,
  ephemeralCompressedHex: string
): Promise<CryptoKey> {
  const saltInput = concatBytes(
    SALT_LABEL,
    hexToBytes(recipientXHex),
    hexToBytes(ephemeralCompressedHex)
  );
  const salt = await sha256Bytes(saltInput);

  const hkdfKey = await crypto.subtle.importKey("raw", toArrayBuffer(sharedSecret), "HKDF", false, ["deriveBits"]);
  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: toArrayBuffer(salt),
      info: toArrayBuffer(HKDF_INFO),
    },
    hkdfKey,
    256
  );

  return crypto.subtle.importKey("raw", derivedBits, "AES-GCM", false, ["encrypt", "decrypt"]);
}

async function sha256Bytes(data: Uint8Array): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.digest("SHA-256", toArrayBuffer(data)));
}

function concatBytes(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}


function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

function hexToBytes(hex: string): Uint8Array {
  const normalized = hex.replace(/^0x/i, "").toLowerCase();
  if (normalized.length % 2 !== 0) {
    throw new Error("Invalid hex string length");
  }
  const out = new Uint8Array(normalized.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = parseInt(normalized.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) {
      throw new Error("Invalid hex string");
    }
    out[i] = byte;
  }
  return out;
}

function bytesToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function base64UrlToBytes(input: string): Uint8Array {
  const normalized = input.replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalized + "=".repeat((4 - (normalized.length % 4)) % 4);
  const binary = atob(padded);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    out[i] = binary.charCodeAt(i);
  }
  return out;
}

/**
 * Verifies that a private key matches a public key.
 */
export function verifyKeyPair(privateKeyHex: string, publicKeyHex: string): boolean {
  const normalizedPrivate = privateKeyHex.replace(/^0x/i, "").toLowerCase();
  const normalizedPublic = publicKeyHex.replace(/^0x/i, "").toLowerCase();

  try {
    const key = curve.keyFromPrivate(normalizedPrivate, "hex");
    const derivedPublic = key.getPublic().getX().toString(16).padStart(64, "0");
    return derivedPublic === normalizedPublic;
  } catch {
    return false;
  }
}
