id = "zfruit"
log_format = "full"

rest_server_port = 9002
rest_server_max_body_size = 10_485_760               # 10 MB
default_faucet_amount = 10
node_url = "http://127.0.0.1:4321"
data_directory = "data"
da_read_from = "127.0.0.1:4141"
buffer_blocks = 0
max_txs_per_proof = 32
tx_working_window_size = 128
utxo_contract_name = "hyli_utxo"
utxo_state_contract_name = "hyli-utxo-state"
smt_incl_proof_contract_name = "hyli_smt_incl_proof"
persist_encrypted_notes = true

indexer_database_url = "postgresql://postgres:postgres@localhost:5432/hyli_indexer"

listener_poll_interval_secs = 60

auto_prover_idle_flush_interval_secs = 2
auto_prover_tx_buffer_size = 5
