id = "zfruit"
log_format = "full"

rest_server_port = 9002
rest_server_max_body_size = 10_485_760 # 10 MB
contract_name = "hyli_utxo"
default_faucet_amount = 10
node_url = "http://127.0.0.1:4321"
data_directory = "data"
da_read_from = "127.0.0.1:4141"
buffer_blocks = 0
max_txs_per_proof = 32
tx_working_window_size = 128
utxo_contract_name = "hyli_utxo"
utxo_state_contract_name = "hyli-utxo-state"
